<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="DRuGLORD" failures="9" tests="16" name="com.cab.cucumber.runners.Runner" time="57.771" errors="0" timestamp="2025-07-26T15:43:08 IST" skipped="0">
  <testcase classname="com.cab.cucumber.runners.Runner" name="runScenario" time="3.252">
    <failure message="expected [true] but found [false]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertTrue(Assert.java:57)
at org.testng.Assert.assertTrue(Assert.java:67)
at com.cab.cucumber.definitions.Booking.verify_the_invalid_data(Booking.java:79)
at ✽.verify the invalid data(file:///C:/Users/hp/eclipse-workspace/AgileQADelivery-TTP1QESA2520-Group5/src/test/java/com/cab/cucumber/features/Booking.feature:19)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <testcase classname="com.cab.cucumber.runners.Runner" name="runScenario" time="3.333">
    <failure message="expected [true] but found [false]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertTrue(Assert.java:57)
at org.testng.Assert.assertTrue(Assert.java:67)
at com.cab.cucumber.definitions.Booking.verify_the_invalid_data(Booking.java:79)
at ✽.verify the invalid data(file:///C:/Users/hp/eclipse-workspace/AgileQADelivery-TTP1QESA2520-Group5/src/test/java/com/cab/cucumber/features/Booking.feature:19)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <testcase classname="com.cab.cucumber.runners.Runner" name="runScenario" time="5.978"/>
  <testcase classname="com.cab.cucumber.runners.Runner" name="runScenario" time="3.309">
    <failure message="expected [true] but found [false]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertTrue(Assert.java:57)
at org.testng.Assert.assertTrue(Assert.java:67)
at com.cab.cucumber.definitions.Booking.verify_the_invalid_data(Booking.java:79)
at ✽.verify the invalid data(file:///C:/Users/hp/eclipse-workspace/AgileQADelivery-TTP1QESA2520-Group5/src/test/java/com/cab/cucumber/features/Booking.feature:19)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <testcase classname="com.cab.cucumber.runners.Runner" name="runScenario" time="3.278">
    <failure message="expected [true] but found [false]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertTrue(Assert.java:57)
at org.testng.Assert.assertTrue(Assert.java:67)
at com.cab.cucumber.definitions.Booking.verify_the_invalid_data(Booking.java:79)
at ✽.verify the invalid data(file:///C:/Users/hp/eclipse-workspace/AgileQADelivery-TTP1QESA2520-Group5/src/test/java/com/cab/cucumber/features/Booking.feature:19)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <testcase classname="com.cab.cucumber.runners.Runner" name="runScenario" time="3.513">
    <failure message="expected [true] but found [false]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertTrue(Assert.java:57)
at org.testng.Assert.assertTrue(Assert.java:67)
at com.cab.cucumber.definitions.Booking.verify_the_invalid_data(Booking.java:79)
at ✽.verify the invalid data(file:///C:/Users/hp/eclipse-workspace/AgileQADelivery-TTP1QESA2520-Group5/src/test/java/com/cab/cucumber/features/Booking.feature:19)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <testcase classname="com.cab.cucumber.runners.Runner" name="runScenario" time="2.603"/>
  <testcase classname="com.cab.cucumber.runners.Runner" name="runScenario" time="3.373">
    <failure message="expected [true] but found [false]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertTrue(Assert.java:57)
at org.testng.Assert.assertTrue(Assert.java:67)
at com.cab.cucumber.definitions.Booking.verify_the_invalid_data(Booking.java:79)
at ✽.verify the invalid data(file:///C:/Users/hp/eclipse-workspace/AgileQADelivery-TTP1QESA2520-Group5/src/test/java/com/cab/cucumber/features/Booking.feature:19)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <testcase classname="com.cab.cucumber.runners.Runner" name="runScenario" time="3.644">
    <failure message="expected [true] but found [false]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertTrue(Assert.java:57)
at org.testng.Assert.assertTrue(Assert.java:67)
at com.cab.cucumber.definitions.Booking.verify_the_invalid_data(Booking.java:79)
at ✽.verify the invalid data(file:///C:/Users/hp/eclipse-workspace/AgileQADelivery-TTP1QESA2520-Group5/src/test/java/com/cab/cucumber/features/Booking.feature:19)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <testcase classname="com.cab.cucumber.runners.Runner" name="runScenario" time="2.513"/>
  <testcase classname="com.cab.cucumber.runners.Runner" name="runScenario" time="3.865">
    <failure message="expected [true] but found [false]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertTrue(Assert.java:57)
at org.testng.Assert.assertTrue(Assert.java:67)
at com.cab.cucumber.definitions.Booking.verify_the_invalid_data(Booking.java:79)
at ✽.verify the invalid data(file:///C:/Users/hp/eclipse-workspace/AgileQADelivery-TTP1QESA2520-Group5/src/test/java/com/cab/cucumber/features/Booking.feature:19)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <testcase classname="com.cab.cucumber.runners.Runner" name="runScenario" time="2.470"/>
  <testcase classname="com.cab.cucumber.runners.Runner" name="runScenario" time="2.512"/>
  <testcase classname="com.cab.cucumber.runners.Runner" name="runScenario" time="3.638">
    <failure message="expected [true] but found [false]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertTrue(Assert.java:57)
at org.testng.Assert.assertTrue(Assert.java:67)
at com.cab.cucumber.definitions.Booking.verify_the_invalid_data(Booking.java:79)
at ✽.verify the invalid data(file:///C:/Users/hp/eclipse-workspace/AgileQADelivery-TTP1QESA2520-Group5/src/test/java/com/cab/cucumber/features/Booking.feature:19)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <testcase classname="com.cab.cucumber.runners.Runner" name="runScenario" time="3.363"/>
  <testcase classname="com.cab.cucumber.runners.Runner" name="runScenario" time="7.127"/>
</testsuite> <!-- com.cab.cucumber.runners.Runner -->
